### ISSUE TITLE
Method colors not consistant.

### ISSUE THREAD

**Issue by escofield** [GeorgeAlexandria/CoCo#11]
trying to get methods color'd yellow.  Not all methods are working correctly, not sure if this is CoCo or something else.  Both methods and extension methods are colored exactly the same. 

I have attached my screenshot.
![capture](https://user-images.githubusercontent.com/3423583/30763887-0b277954-9fae-11e7-8a11-8e93b66db5d7.PNG)
![capture2](https://user-images.githubusercontent.com/3423583/30763943-54d8196e-9fae-11e7-84f1-213feab7cce2.PNG)

**Comment by escofield** [comment]
and..  i noticed a pattern,  the variables that are working,  are explicitly typed.  The others are declared as var.

**Comment by escofield** [comment]
this is due to the cs file being opened independent of the solution/project.  It looks completely different otherwise.

**Comment by GeorgeAlexandria** [comment]
@escofield You are right, this is due for files were opened independent. I have an opened issue for it. You can track #2.
