### ISSUE TITLE
Bold selection not working

### ISSUE THREAD

**Issue by Troncho** [GeorgeAlexandria/CoCo#12]
Hi, when you check the **Bold** checkbox on Coco Format..., nothing happens.

**Comment by GeorgeAlexandria** [comment]
@Troncho, you can check a new version of extension. So let me know if you have still issues with bold fonts.

**Comment by GeorgeAlexandria** [comment]
@Troncho, Do you have a still this issue with the bold selection for items?

**Comment by Troncho** [comment]
Thanks, it works fine now 😊

Marcelo Mejail
