### ISSUE TITLE
List of default colours

### ISSUE THREAD

**Issue by strandloper** [GeorgeAlexandria/CoCo#5]
I understand not wanting to set colours by default but it's tricky to choose a colour scheme that works well. From your screen shots you have obviously spent some time doing this. Perhaps you might include a list of the values you have set for the various CoCo colour settings. We could still apply them manually bit would have your list as a guide. If your colour choices differ for the light and dark themes please supply a list of colours you chose for each.

**Comment by GeorgeAlexandria** [comment]
Thanks for suggestion! I added a lists of colour settings from examples to readme for the both of themes. 
I hope it will helpful.

**Comment by strandloper** [comment]
Thank you
