### ISSUE TITLE
Supports Visual Studio 2019

### ISSUE THREAD

**Issue by GeorgeAlexandria** [GeorgeAlexandria/CoCo#55]

**Comment by MPasadu** [comment]
Hey George,

love your extension! 
Do you have any approximate release date for VS2019 support?

Best regards

**Comment by GeorgeAlexandria** [comment]
@MPasadu, thanks for you feedback!

I haven't looked at yet how many internal things was changed in the Visual Studio 2019, therefore I don't know how much changes CoCo must do, but I'm hope that the next release will be to the end of May

**Comment by GeorgeAlexandria** [comment]
Hello, @MPasadu.

The last 3.2.0 version CoCo supports Visual Studio 2019, so you can check out them.
