### ISSUE TITLE
Cannot uninstall as non-admin user

### ISSUE THREAD

**Issue by Robert-Mattingly** [GeorgeAlexandria/CoCo#6]
CoCo installed successfully as a non-admin user, however, uninstall as non-admin fails due to System.UnauthorizedAccessException.    The specific registry key is \Software\Microsoft\VisualStudio\[User_Dir]\ExtensionManager\PendingDeletions'.

**To Reproduce:**
1. Log into non-admin account in Windows 7.
2. Install package in Visual Studio from Extensions and Updates.
3. Restart Visual Studio and uninstall from Extensions and Updates.

**Comment by Robert-Mattingly** [comment]
I've attempted to uninstall for my user, but even through the command line, VSIXINSTALLER.exe can't touch it.  I need to be an admin to uninstall, but the admin account doesn't have the extension.  Any suggestions would be greatly appreciated.

**Comment by Robert-Mattingly** [comment]
Resetting my privateregistry.user.bin cleared the access denied issue with the registry, and allowed me to uninstall.  Not sure if this is something in my environment which is unique (entirely possible) or if the extension in some way caused a problem with my privateregistry.user.bin.

**Comment by GeorgeAlexandria** [comment]
@Robert-Mattingly [here](https://github.com/GeorgeAlexandria/CoCo/issues/7#issuecomment-328098662) you said that the problem was specific to that environment. Is current issue still valid or not?

**Comment by Robert-Mattingly** [comment]
@GeorgeAlexandria only for that environment.  Both issues disappeared when switching environments.  I'm not 100% sure what the underlying problem is but based on our successes when testing in a Win7 environment, I'm confident that it must be that environment in particular and not a problem in your vsix.

I'd love to dig into the exact reason things went wrong, but it's overly-complicated to run diagnostics in that environment and *definitely* not worth taking up your time.  Thank you for working with me on this.
