### ISSUE TITLE
Static properties doesn't show bold

### ISSUE THREAD

**Issue by PieroAlvarez** [GeorgeAlexandria/CoCo#65]
I recently move from Visual Studio 2017 to **2019** and when i set the **Properties** to bold, only the instance properties shows bold; the static properties are not affected.

The same problem with the rest of decorators but the colors and the rendering size works fine.

**Comment by GeorgeAlexandria** [comment]
@PieroAlvarez,  thanks for your attention!
Seems that bold font not working for all static members, not just properties. By the way, I didn't find case when decorations have the different behavior for static and instance members.

**Comment by GeorgeAlexandria** [comment]
@PieroAlvarez, the new version of CoCo which include the fix of this issue was released, so you can check it.

**Comment by PieroAlvarez** [comment]
Works perfectly.

Thank you mate :-D
