### ISSUE TITLE
Highlighting not working correctly for conditional code

### ISSUE THREAD

**Issue by strandloper** [GeorgeAlexandria/CoCo#67]
When using conditional code, i.e. `#if DEBUG ... #else ... #endif` the code highlighting does not correctly follow changes in the conditional state, such as switching between Release and Debug profiles. 

In the attached image, the top screenshot shows some code in a file that was opened while  the **Release** profile was selected and the lower shows how it changed when the profile was changed to **Debug**. The code in the `#else` should have become all grey but did not. When it was changed back to **Release** the display reverted to the top screenshot.

Versions are Visual Studio 2019 16.3.1 and CoCo 3.2.1

![coco](https://user-images.githubusercontent.com/668433/66302502-56aa1a80-e8f9-11e9-8449-fd3ba9133f13.png)

**Comment by GeorgeAlexandria** [comment]
@strandloper, thanks for your attention!
The new version of CoCo which include the fix of this issue was released, so you can check it.
