### ISSUE TITLE
Installation on VS instance breaks Dark Theme

### ISSUE THREAD

**Issue by Robert-Mattingly** [GeorgeAlexandria/CoCo#7]
Installed on Visual Studio 2017 on Windows 7, where I was using the default dark theme.  The installation immediately applied a light color scheme to the Text Editor only, and I cannot undo this.  Additionally, as I can't uninstall the extension, I don't know if an uninstall will reset my colors.  

**To Reproduce:**
Install Extension on VS2017 which is set to use default dark theme.

**Comment by Robert-Mattingly** [comment]
I managed to get my Text Editor colors reset by deleting by privateregistry.user.bin file.  This is a possible workaround until I can uninstall.

**Comment by GeorgeAlexandria** [comment]
Thanks for your feedback.

It's very strange behavior that installation applied a light theme to the Text Editor. I tested installation to both of themes at Windows 10/8.1 and it works as well, hovewer, I didn't test it at Windows 7. 

Anyway, I will try to install it to the [develop Windows 7](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) at this week and will try to investigate your problem from this issue and from #6 issue

**Comment by wholemy** [comment]
This is a recurring problem that arises in consequence of the installation of different extensions, I override all colors in my extension) Lose theme settings from install new extensions randomly) It bugs in Visual Studio)

**Comment by Robert-Mattingly** [comment]
I tested on different machines and it works fine.  Looks like the issue is specific to that environment.  Thank you for looking into this, and sorry I didn't think to try that first.
