### ISSUE TITLE
Large number of NullReferenceExceptions in ActivityLog.xml when opening F# project first

### ISSUE THREAD

**Issue by BlueNinjaSoftware** [GeorgeAlexandria/CoCo#8]
When I open an F# project in Visual Studio 2017, I get an error dialog indicating that an exception has occurred, and to check the ActivityLog.xml file for details. The file contains several dozen of the following error:

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at CoCo.EditorClassifier.GetClassificationSpans(SnapshotSpan span)
>   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext()
>   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__39.MoveNext()

Possibly, the classification should not be happening on F# projects and a language filter is needed?

**Comment by GeorgeAlexandria** [comment]
Well, at this moment syntax analyzing should not be happens on F# projects, so it's a bug. But it will have not been a bug after issue #2 will be done. 

I will disable it at this week as temporary solution, but I would be greatly appreciated if you can post a few examples to the future works.

**Comment by BlueNinjaSoftware** [comment]
I will certainly post further details as I uncover them. Thanks!

**Comment by GeorgeAlexandria** [comment]
@BlueNinjaSoftware, you can check a new version of extension. So let me know if you have still exceptions.

**Comment by BlueNinjaSoftware** [comment]
Looks good now, thanks!
